### ISSUE TITLE
"uuid: not found", "parted: not found"

### ISSUE THREAD

**Issue by VictorGrycuk** [tom-2015/imgclone#12]
Hi!
I was trying to use imgclone to make a backup of my [OSMC](https://osmc.tv/) image, but I was getting the following message when trying to run the `make `command:
```shell
osmc@HTPC:~/imgclone$ make
gcc -g -I/usr/include -L/usr/lib -L/usr/local/lib -I/usr/lib/arm-linux-gnueabihf -pthread imgclone.c -o imgclone
imgclone.c:32:10: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:8: imgclone] Error 1
```

I was able to fix this by running `sudo apt-get install libc6-dev`, as per [this SO answer](https://stackoverflow.com/questions/19580758/gcc-fatal-error-stdio-h-no-such-file-or-directory). I am using the version `2021.08-1` of OSMC on a Raspberry Pi 4 B+.
Could this be a missing dependency for this OS?

In any case, after this, I ran the `imgclone -d mybackup.img` command, but I am getting the following message:

```shell
Cloning /dev/mmcblk0 to mybackup.img
uuid | cut -f1 -d-
sh: 1: uuid: not found
sh: 1: parted: not found
Unable to read source.
```

Any idea what could it be?
Thanks!

**Comment by tom-2015** [comment]
It's also some commands that are not installed on OSMC I think.
Try:
`sudo apt-get install uuid parted`

**Comment by VictorGrycuk** [comment]
Thank you, that solved the problem!
I was able to create the image.

Thanks for the help, I will close the issue.
