### ISSUE TITLE
Error: Can't have a partition outside the disk!

### ISSUE THREAD

**Issue by kevinlinxc** [tom-2015/imgclone#18]
While cloning I see:
`Error: Can't have a partition outside the disk!`

Why is this? Is it an issue?

E.g. 

<img width="789" alt="image" src="https://github.com/tom-2015/imgclone/assets/44324811/e9488a4e-a14a-4c04-abd3-7e8acce2ac92">

**Comment by tom-2015** [comment]
I think one of the partitions goes beyond the size of the created .img file. What is the command you used?

**Comment by kevinlinxc** [comment]
I believe I ran `imgclone -d mybackup.img`. I was running on a USB, ideally I could do it over SSH but I don't know if that's possible/how to do it. My friend just used another GUI program to copy the sd card.
