### ISSUE TITLE
Feature request: bzip2 etc image file compression option.

### ISSUE THREAD

**Issue by CaptainMidnight** [tom-2015/imgclone#2]
A great cli based tool for image creation of a live RPi OS. Although the resultant .img file is only slightly more than the original used space source - is there a possibility of including a post image creation bzip2 or similar image compression option within your script.

This would create potentially a much smaller compressed .img file for archive/storage/transport and could be used as is with most of the image writers to recreate boot media from a compressed .img file.

**Comment by CaptainMidnight** [comment]
A compressed image aids transmission etc. As an example, a 32GB SDcard, created an image of 7.73GB, which after bz2 compression reduced to 2.05GB.

**Comment by tom-2015** [comment]
I'm not sure if it is possible to do this directly while creating the image. Compressing the image after backup is made will the easiest way I think.

**Comment by CaptainMidnight** [comment]
Yeah that's what I was thinking, it's not like a piped dd operation, so would need to be an additional optional step after image file creation.

I currently do a simple 'bzip2 image-file.img' command manually after your script has ran, that automatically removes the original .img file, leaving just the compressed image file.

Just thought I'd ask if you could include that option as part of your script, as .bz2 compressed image files for example can be used directly with many of the SDcard creation tools.

**Comment by tom-2015** [comment]
I've added bzip2 and gzip compression with -gzip and -bzip2 arguments but when I try to compress the image with bzip2 I get:

`bzip2: Can't open input file test.img: Value too large for defined data type.`

**Comment by CaptainMidnight** [comment]
I'm no 'c' programmer, but now that I've seen how you've added the options I'll have a look, theoretically it's just calling an external program and passing it the single parameter of the file name.

**Comment by CaptainMidnight** [comment]
Ok I've been running some tests: -
Run 1 - test1.img 7.74GB
Run 2 - test2.img.gz 2.24GB
Run 3 - in progress will update on completion - update completed fine test3.img.bz2 2.05GB - job done!

(By manual bzip2, output should be 2.05GB, currently monitoring final bzip2 of imgclone via remote 'ls -l' currently 1/3 of the way through 7.70GB)

Tests carried out creating backups to a LAN based samba share.

**Comment by CaptainMidnight** [comment]
Tests carried out successfully, thanks for the feature.
