### ISSUE TITLE
Installation instructions refer to an incorrect directory.

### ISSUE THREAD

**Issue by GOTO-GOSUB** [tom-2015/imgclone#4]
Readme.md contains a typo:

> Installation
> On the raspberry you open a terminal window and type following commands:
> 
> sudo apt-get update
> sudo apt-get install gcc make git
> git clone https://github.com/tom-2015/imgclone.git
> cd imageclone

That last line should be

> cd imgclone

**Comment by tom-2015** [comment]
fixed
